name: Periodic Netlify Build

# runs monday/wednesday/friday at 04:00 UTC (early morning)
on:
    schedule:
        - cron: '0 4 * * 1,3,5'

jobs:
    trigger-netlify-build:
        runs-on: ubuntu-latest
        steps:
            - run: curl -X POST ${{ secrets.NETLIFY_BUILD_HOOK }}
